version: '3.3'
services:
  dp:
    build: ./dp
    volumes:
      - ./dp/config/:/opt/ibm/datapower/drouter/config
      #- ./dp/local/:/opt/ibm/datapower/drouter/local
    ports:
      - "9090:9090"
      - "5554:5554"
      - "8443:8443"
    expose:
      - "9090"
      - "5554"
      - "8443"
    environment:
      - "DATAPOWER_ACCEPT_LICENSE=true"
      - "DATAPOWER_INTERACTIVE=true"
