name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible==2.10.7
          pip install ansible-base==2.10.10
          pip install ansible-bender==0.8.1
          pip install ansible-lint==5.0.11
          pip install voluptuous
          pip install -r ansible_collections/community/datapower/requirements.txt; 
          
      - name: Integration Tests
        run: |
          python --version
          which python
          chmod 777 dp/config dp/local
          docker-compose up -d
          sleep 30
          cd ansible_collections/community/datapower && ansible-test network-integration

      - name: Build package
        working-directory: ansible_collections/community/datapower
        run: |
          ansible-galaxy collection build --force