name: Unit and Sanity Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible==2.10.7
          pip install ansible-base==2.10.10
          pip install ansible-bender==0.8.1
          pip install ansible-lint==5.0.11
          pip install voluptuous
          pip install pycodestyle
          pip install -r ansible_collections/community/datapower/requirements.txt;

      - name: Sanity tests
        working-directory: ansible_collections/community/datapower
        run: |
          ansible-test sanity --test validate-modules
          ansible-test sanity --test pep8 plugins/modules/
          ansible-test sanity --test line-endings

      - name: Unit tests
        working-directory: ansible_collections/community/datapower
        run: |
          ansible-test units \
           --python ${{ matrix.python-version }} \
           --venv -v tests/unit/module_utils/datapower/